export const BOOSTED_WORDS = [
  // Immediate Family & Close Relations
  "محمد",
  "راشد",
  "زايد",
  "هند",
  "شيخة",
  "مكتوم",
  "أحمد",
  "حمدان",
  "فلذة",
  "نور",
  "حبيبي",
  "أمي",
  "أبي",
  "ابني",
  "ابنتي",
  "أخي",
  "بنتي",
  "ابنتي",
  "فرحتي",

  // Leadership & Founding Fathers
  "بو خالد",
  "MBZ",
  "خليفة",
  "سعود",
  "صقر",
  "حميد",
  "نائب",
  "راشد بن سعيد",
  "مكتوم بن راشد",
  "زايد بن سلطان",
  "حاكم دبي",
  "حاكم أبوظبي",
  "حاكم الشارقة",
  "حاكم الفجيرة",
  "حاكم رأس الخيمة",
  "حاكم عجمان",
  "رئيس الدولة",
  "رئيس الوزراء",

  // Core National & Pride Terms
  "الوطن",
  "الإمارات",
  "دبي",
  "أبوظبي",
  "الشارقة",
  "الفجيرة",
  "رأس الخيمة",
  "عجمان",
  "أم القيوين",
  "الشهداء",
  "الجنود",
  "المواطنين",
  "شعب الإمارات",
  "الآباء المؤسسين",
  "العلم",
  "الراية",
  "المجد",
  "الفخر",
  "الكرامة",
  "الوفا",
  "العروبة",
  "الأمل",
  "الزمن",

  // Common Poetic Words / Love Language
  "حب",
  "عشق",
  "قلب",
  "العيون",
  "الشوق",
  "الغلا",
  "الهجر",
  "الفراق",
  "الوصل",
  "الهوى",
  "الغرام",
  "المحبين",
  "الاشواق",
  "الحنين",
  "الوجد",
  "اللوعة",
  "الشجن",
  "الجروح",
  "الألم",
  "الدموع",
  "الحزن",
  "المحاني",
  "العذال",
  "الصد",
  "الهجران",
  "الملام",

  // Key Events & Cultural Terms
  "يوم الشهيد",
  "اليوم الوطني",
  "يوم العلم",
  "يوم الاتحاد",
  "رمضان",
  "عيد الفطر",
  "عيد الأضحى",
  "يوم عرفة",
  "رأس السنة الهجرية",
  "المولد النبوي",
  "يوم الأم",
  "تحدي دبي للياقة",
  "مهرجان دبي للتسوق",
  "مفاجآت دبي الصيفية",
  "معرض دبي للطيران",
  "جائزة أبوظبي الكبرى",
  "كأس دبي العالمي",
  "expo 2020",

  // Pan-Arab / Regional References
  "مصر",
  "فلسطين",
  "المغرب",
  "بغداد",
  "الشام",
  "سلمان",
  "تميم",
  "حمد",
  "مشعل",
  "هيثم",
  "محمد بن سلمان",
  "MBS",

  // Miscellaneous Boosters from Poetry Style
  "ليل",
  "العطر",
  "العشق",
  "الروح",
  "الحياة",
  "الدنيا",
  "الصبر",
  "الأمل",
  "المجد",
  "السماء",
  "الأرض",
  "الهواء",
  "الثرا",
  "الماء",
  "البحر",
  "الشمس",
  "القمر",
];

// Latin to Arabic mapping
export const LATIN_TO_ARABIC = {
  // Names & Family
  mohamed: "محمد",
  mohammad: "محمد",
  ahmed: "أحمد",
  hmd: "حمد",
  hamdan: "حمدان",
  hind: "هند",
  sheikha: "شيخة",
  mktoum: "مكتوم",
  bin: "بن",
  ibn: "بن",

  // Leadership & Royalty
  mbz: "محمد بن زايد",
  zayed: "زايد",
  zxayed: "زايد",
  khalifa: "خليفة",
  saud: "سعود",
  saqr: "صقر",
  hamid: "حميد",
  rashed: "راشد",
  rashid: "راشد",
  "rashid bin said": "راشد بن سعيد",
  "maktoum bin rashid": "مكتوم بن راشد",
  "zayed bin sultan": "زايد بن سلطان",
  "ruler of dubai": "حاكم دبي",
  "ruler of abu dhabi": "حاكم أبوظبي",
  "ruler of sharjah": "حاكم الشارقة",
  "ruler of fujairah": "حاكم الفجيرة",
  "ruler of ras al khaimah": "حاكم رأس الخيمة",
  "ruler of ajman": "حاكم عجمان",
  "vice president": "نائب رئيس الدولة",
  "prime minister": "رئيس الوزراء",

  // National & Cultural terms
  home: "الوطن",
  uae: "الإمارات",
  dubai: "دبي",
  abudhabi: "أبوظبي",
  sharjah: "الشارقة",
  fujairah: "الفجيرة",
  "ras alkhaimah": "رأس الخيمة",
  ajman: "عجمان",
  "um alqaiwain": "أم القيوين",
  martyrs: "الشهداء",
  soldiers: "الجنود",
  people: "شعب الإمارات",
  "founding father": "الآباء المؤسسين",
  flag: ["العلم", "الراية"],
  glory: ["المجد"],
  pride: ["الفخر"],
  dignity: ["الكرامة"],
  loyalty: ["الوفا"],
  arob: ["العروبة"],
  hope: ["الأمل"],
  time: ["الزمن"],

  // Poetic / love
  love: "حب",
  passion: "عشق",
  heart: "قلب",
  eyes: "العيون",
  longing: "الشوق",
  affection: "الغلا",
  separation: "الهجر",
  parting: "الفراق",
  union: "الوصل",
  desire: "الهوى",
  romance: "الغرام",
  lovers: "المحبين",
  longings: "الاشواق",
  nostalgia: "الحنين",
  existence: "الوجد",
  anguish: "اللوعة",
  melancholy: "الشجن",
  wounds: "الجروح",
  pain: "الألم",
  sorrow: "الحزن",
  afflictions: "المحاني",
  reproaches: "العذال",
  rejection: "الصد",
  abandonment: "الهجران",
  reproach: "الملام",
  night: "ليل",
  perfume: "العطر",
  soul: "الروح",
  life: "الحياة",
  world: "الدنيا",

  // Events & holidays
  "martyrs day": "يوم الشهيد",
  "national day": "اليوم الوطني",
  "flag day": "يوم العلم",
  "union day": "يوم الاتحاد",
  ramadan: "رمضان",
  "eid al fitr": "عيد الفطر",
  "eid al adha": "عيد الأضحى",
  "arafah day": "يوم عرفة",
  "hijri new year": "رأس السنة الهجرية",
  "mawlid al nabawi": "المولد النبوي",
  "mothers day": "يوم الأم",

  "dubai fitness challenge": "تحدي دبي للياقة",
  "dubai shopping festival": "مهرجان دبي للتسوق",
  "dubai summer surprises": "مفاجآت دبي الصيفية",
  "dubai airshow": "معرض دبي للطيران",
  "abu dhabi grand prix": "جائزة أبوظبي الكبرى",
  "dubai world cup": "كأس دبي العالمي",
  expo2020: "expo 2020",

  // Pan-Arab / Regional (UAE-relevant)
  egypt: "مصر",
  palestine: "فلسطين",
  morocco: "المغرب",
  baghdad: "بغداد",
  sham: "الشام",

  // GCC (Closest to UAE)
  uae: "الإمارات",
  dubai: "دبي",
  abu_dhabi: "أبوظبي",
  sharjah: "الشارقة",

  saudi: "السعودية",
  ksa: "السعودية",
  riyadh: "الرياض",
  jeddah: "جدة",

  oman: "عُمان",
  muscat: "مسقط",

  kuwait: "الكويت",

  qatar: "قطر",
  doha: "الدوحة",

  bahrain: "البحرين",
  manama: "المنامة",

  // Nearby Arab states with strong relation
  jordan: "الأردن",
  amman: "عمّان",

  iraq: "العراق",
  basra: "البصرة",

  syria: "سوريا",
  damascus: "دمشق",

  lebanon: "لبنان",
  beirut: "بيروت",

  yemen: "اليمن",
  sanaa: "صنعاء",

  // North Africa (frequent cultural ties)
  tunisia: "تونس",
  algeria: "الجزائر",
  libya: "ليبيا",
  sudan: "السودان",

  salman: "سلمان",
  tamim: "تميم",
  mishal: "مشعل",
  haitham: "هيثم",
  "mohamed bin salman": "محمد بن سلمان",
  mbs: "MBS",

  // Elements / natural
  perfume: "العطر",
  love: "العشق",
  soul: "الروح",
  life: "الحياة",
  world: "الدنيا",
  patience: "الصبر",
  hope: "الأمل",
  sky: "السماء",
  earth: "الأرض",
  air: "الهواء",
  soil: "الثرا",
  water: "الماء",
  sea: "البحر",
  sun: "الشمس",
  moon: "القمر",
};
